import { useEffect, useState } from 'react';
import { AlertCircle, ArrowUpRight, ChevronLeft, ChevronRight, Globe2, Search } from 'lucide-react';
import { useCountries } from '../context/CountryContext';
import { countryNumber } from '../services/countryFormat';
import CountryFlag from './CountryFlag';
import LoadingSpinner from './LoadingSpinner';

export default function CountriesTable({ onSelectCountry }) {
  const { countries, filters, page, pageSize, sort, setPage, setPageSize, setSort, setFilters, tableLoading, tableError, refresh } = useCountries();
  const [search, setSearch] = useState(filters.search);
  useEffect(() => { setSearch(filters.search); }, [filters.search]);
  useEffect(() => { if (search === filters.search) return; const timeout = setTimeout(() => setFilters({ search }), 350); return () => clearTimeout(timeout); }, [search, filters.search, setFilters]);
  const pagination = countries?.pagination;
  const start = pagination?.total ? (page - 1) * pageSize + 1 : 0;
  return <section className="orders-section country-table-section" aria-label="Country table"><div className="orders-heading"><div><h2>Countries and territories<span className="count-badge">{pagination?.total || 0}</span></h2><p>Population, geography and currency relationships</p></div><div className="table-tools">{tableLoading && <LoadingSpinner small label="Updating" />}<select className="country-sort" aria-label="Sort countries" value={sort} onChange={(event) => setSort(event.target.value)}><option value="population_desc">Population: highest</option><option value="density_desc">Density: highest</option><option value="area_desc">Area: largest</option><option value="name_asc">Name: A-Z</option></select><label className="search-input"><Search size={16} /><input aria-label="Search countries" placeholder="Search countries..." value={search} onChange={(event) => setSearch(event.target.value)} /></label></div></div>
    {tableError ? <div className="error-banner" role="alert"><AlertCircle size={17} /><span>{tableError}</span><button className="button" onClick={refresh}>Retry</button></div> : <>
      <div className={`table-scroll ${tableLoading ? 'is-updating' : ''}`} aria-busy={tableLoading}><table><thead><tr><th>Country</th><th>Region</th><th>Currencies</th><th className="number-cell">Population</th><th className="number-cell">Area (km2)</th><th className="number-cell">People/km2</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{countries?.data.map((country) => <tr key={country.code}><td><button className="country-name-button" onClick={() => onSelectCountry(country.code)}><CountryFlag key={country.flag_url} url={country.flag_url} name={country.name} /><span>{country.name}<small>{country.code}</small></span></button></td><td className="muted-cell">{country.region}</td><td><span className="country-currency-cell">{country.currencies.map((entry) => entry.code).join(', ') || '--'}</span></td><td className="number-cell amount-cell">{countryNumber(country.population)}</td><td className="number-cell muted-cell">{countryNumber(country.area_km2)}</td><td className="number-cell amount-cell">{countryNumber(country.density)}</td><td><button className="icon-button row-open" title={`Open ${country.name}`} aria-label={`Open ${country.name}`} onClick={() => onSelectCountry(country.code)}><ArrowUpRight size={16} /></button></td></tr>)}</tbody></table>
        {!tableLoading && !countries?.data.length && <div className="table-empty"><Globe2 size={28} /><h3>No countries found</h3><p>No records match these filters.</p></div>}{tableLoading && !countries && <div className="table-empty"><LoadingSpinner label="Loading countries" /></div>}</div>
      <div className="table-footer"><span>{start}-{Math.min(page * pageSize, pagination?.total || 0)} of {pagination?.total || 0} countries</span><div className="pagination"><label className="rows-per-page">Rows<select aria-label="Countries per page" value={pageSize} onChange={(event) => setPageSize(Number(event.target.value))}><option value={10}>10</option><option value={20}>20</option><option value={50}>50</option></select></label><span>Page {page} of {Math.max(1, pagination?.total_pages || 0)}</span><button className="icon-button" title="Previous country page" aria-label="Previous country page" disabled={page <= 1 || tableLoading} onClick={() => setPage(page - 1)}><ChevronLeft size={17} /></button><button className="icon-button" title="Next country page" aria-label="Next country page" disabled={!pagination || page >= pagination.total_pages || tableLoading} onClick={() => setPage(page + 1)}><ChevronRight size={17} /></button></div></div>
    </>}
  </section>;
}
